version: 2
updates:
- directory: "/"
  package-ecosystem: github-actions
  schedule:
    interval: daily
    time: "06:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 99
  target-branch: main
  reviewers:
  - Hazmi35
  labels:
  - gh-actions
  commit-message:
    prefix: ci
    include: scope
- directory: "/14/alpine"
  package-ecosystem: docker
  schedule:
    interval: daily
    time: "06:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 99
  target-branch: main
  reviewers:
  - Hazmi35
  labels:
  - update
  commit-message:
    prefix: feat
    include: scope
  ignore:
    - dependency-name: "node"
      versions:
        - ">=15.a"
- directory: "/14/dev/alpine"
  package-ecosystem: docker
  schedule:
    interval: daily
    time: "06:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 99
  target-branch: main
  reviewers:
  - Hazmi35
  labels:
  - update
  commit-message:
    prefix: feat
    include: scope
  ignore:
    - dependency-name: "node"
      versions:
        - ">=15.a"
- directory: "/14/debian"
  package-ecosystem: docker
  schedule:
    interval: daily
    time: "06:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 99
  target-branch: main
  reviewers:
  - Hazmi35
  labels:
  - update
  commit-message:
    prefix: feat
    include: scope
  ignore:
    - dependency-name: "node"
      versions:
        - ">=15.a"
- directory: "/14/dev/debian"
  package-ecosystem: docker
  schedule:
    interval: daily
    time: "06:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 99
  target-branch: main
  reviewers:
  - Hazmi35
  labels:
  - update
  commit-message:
    prefix: feat
    include: scope
  ignore:
    - dependency-name: "node"
      versions:
        - ">=15.a"
- directory: "/16/alpine"
  package-ecosystem: docker
  schedule:
    interval: daily
    time: "06:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 99
  target-branch: main
  reviewers:
  - Hazmi35
  labels:
  - update
  commit-message:
    prefix: feat
    include: scope
  ignore:
    - dependency-name: "node"
      versions:
        - ">=17.a"
- directory: "/16/dev/alpine"
  package-ecosystem: docker
  schedule:
    interval: daily
    time: "06:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 99
  target-branch: main
  reviewers:
  - Hazmi35
  labels:
  - update
  commit-message:
    prefix: feat
    include: scope
  ignore:
    - dependency-name: "node"
      versions:
        - ">=17.a"
- directory: "/16/debian"
  package-ecosystem: docker
  schedule:
    interval: daily
    time: "06:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 99
  target-branch: main
  reviewers:
  - Hazmi35
  labels:
  - update
  commit-message:
    prefix: feat
    include: scope
  ignore:
    - dependency-name: "node"
      versions:
        - ">=17.a"
- directory: "/16/dev/debian"
  package-ecosystem: docker
  schedule:
    interval: daily
    time: "06:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 99
  target-branch: main
  reviewers:
  - Hazmi35
  labels:
  - update
  commit-message:
    prefix: feat
    include: scope
  ignore:
    - dependency-name: "node"
      versions:
        - ">=17.a"
- directory: "/17/alpine"
  package-ecosystem: docker
  schedule:
    interval: daily
    time: "06:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 99
  target-branch: main
  reviewers:
  - Hazmi35
  labels:
  - update
  commit-message:
    prefix: feat
    include: scope
  ignore:
    - dependency-name: "node"
      versions:
        - ">=18.a"
- directory: "/17/dev/alpine"
  package-ecosystem: docker
  schedule:
    interval: daily
    time: "06:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 99
  target-branch: main
  reviewers:
  - Hazmi35
  labels:
  - update
  commit-message:
    prefix: feat
    include: scope
  ignore:
    - dependency-name: "node"
      versions:
        - ">=18.a"
- directory: "/17/debian"
  package-ecosystem: docker
  schedule:
    interval: daily
    time: "06:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 99
  target-branch: main
  reviewers:
  - Hazmi35
  labels:
  - update
  commit-message:
    prefix: feat
    include: scope
  ignore:
    - dependency-name: "node"
      versions:
        - ">=18.a"
- directory: "/17/dev/debian"
  package-ecosystem: docker
  schedule:
    interval: daily
    time: "06:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 99
  target-branch: main
  reviewers:
  - Hazmi35
  labels:
  - update
  commit-message:
    prefix: feat
    include: scope
  ignore:
    - dependency-name: "node"
      versions:
        - ">=18.a"
