version: 2
updates:
- directory: "/14/alpine"
  package-ecosystem: docker
  schedule:
    interval: daily
    time: "06:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 99
  target-branch: main
  reviewers:
  - Hazmi35
  labels:
  - update
  commit-message:
    prefix: feat
    include: scope
  ignore:
    - dependency-name: "node"
      versions: [">14"]
- directory: "/14/dev/alpine"
  package-ecosystem: docker
  schedule:
    interval: daily
    time: "06:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 99
  target-branch: main
  reviewers:
  - Hazmi35
  labels:
  - update
  commit-message:
    prefix: feat
    include: scope
  ignore:
    - dependency-name: "node"
      versions: [">14"]
- directory: "/16/alpine"
  package-ecosystem: docker
  schedule:
    interval: daily
    time: "06:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 99
  target-branch: main
  reviewers:
  - Hazmi35
  labels:
  - update
  commit-message:
    prefix: feat
    include: scope
  ignore:
    - dependency-name: "node"
      versions: [">16"]
- directory: "/16/dev/alpine"
  package-ecosystem: docker
  schedule:
    interval: daily
    time: "06:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 99
  target-branch: main
  reviewers:
  - Hazmi35
  labels:
  - update
  commit-message:
    prefix: feat
    include: scope
  ignore:
    - dependency-name: "node"
      versions: [">16"]
