name: Build & Push 14/dev/alpine to OCI Image Registry

on:
  push:
    branches:
      - main
    paths:
      - "14/dev/alpine/**"
  pull_request:
    branches:
      - main
    paths:
      - "14/dev/alpine/**"

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      workdir: "14/dev/alpine"
      images: |
        docker.io/hazmi35/node
        ghcr.io/hazmi35/node
    secrets:
      docker-hub-username: hazmi35
      docker-hub-access-token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      ghcr-username: ${{ github.repository_owner }}
      ghcr-access-token: ${{ secrets.GITHUB_TOKEN }}
