name: Build & Push OCI Image to OCI Image Registry

on:
  workflow_call:
    inputs:
      workdirs:
        required: true
        type: string
      platforms:
        required: true
        type: string
      tags:
        required: true
        type: string
      labels:
        required: true
        type: string
    secrets:
      docker-hub-username:
        required: true
      docker-hub-access-token:
        required: true
      ghcr-username:
        required: true
      ghcr-access-token:
        required: true

permissions:
  contents: read
  packages: write

jobs:
  build:
    strategy:
      matrix: # REFS: https://github.community/t/reusable-workflow-with-strategy-matrix/205676
        workdir: ${{ fromJSON(inputs.workdirs) }}
        platforms: ${{ fromJSON(inputs.platforms) }}

    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0

      - name: Set up QEMU for Docker Buildx
        uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8 # tag=v2.0.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6 # tag=v2.0.0

      - name: Login to Docker Hub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # tag=v2.0.0
        with:
          registry: docker.io
          username: ${{ secrets.docker-hub-username }}
          password: ${{ secrets.docker-hub-access-token }}

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # tag=v2.0.0
        with:
          registry: ghcr.io
          username: ${{ secrets.ghcr-username }}
          password: ${{ secrets.ghcr-access-token }}

      - name: Build and push the Docker image from the specified Dockerfile
        id: docker_build
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94 # tag=v3.1.1
        with:
          context: ${{ matrix.workdir }}
          platforms: ${{ matrix.platform }}
          push: ${{ github.event_name == 'push' }}
          tags: ${{ inputs.tags }}
          labels: ${{ inputs.labels }}

      # Well, turns out it doesn't support PAT yet. Please see https://github.com/peter-evans/dockerhub-description/issues/24 and https://github.com/docker/roadmap/issues/115
      #- name: Update repo description
      #  uses: peter-evans/dockerhub-description@v2.4.1
      #  with:
      #    username: ${{ secrets.docker-hub-username }}
      #    password: ${{ secrets.docker-hub-username }}
      #    repository: TO BE FILLED
