name: Build & Push OCI Image to OCI Image Registry

on:
  workflow_call:
    inputs:
      workdirs:
        required: true
        type: string
      images:
        required: true
        type: string
    secrets:
      docker-hub-username:
        required: true
      docker-hub-access-token:
        required: true
      ghcr-username:
        required: true
      ghcr-access-token:
        required: true

permissions:
  contents: read
  packages: write

jobs:
  build:
    continue-on-error: true
    strategy:
      matrix: # REFS: https://github.community/t/reusable-workflow-with-strategy-matrix/205676
        workdir: ${{ fromJSON(inputs.workdirs) }}

    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Set up QEMU for Docker Buildx
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # tag=v2.1.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325 # tag=v2.2.1

      - name: Set up Node.js for extracting recipe from Dockerfile
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0

      - name: Extract recipe from Dockerfile
        id: recipe
        run: |
          TAGS=`npm exec -sy @hazmi35/extract-docker-baseimg-recipe ${{ matrix.workdir }}/Dockerfile tags`
          PLATFORMS=`npm exec -sy @hazmi35/extract-docker-baseimg-recipe ${{ matrix.workdir }}/Dockerfile platforms`
          VARIANT=`npm exec -sy @hazmi35/extract-docker-baseimg-recipe ${{ matrix.workdir }}/Dockerfile variant`
          echo TAGS: $TAGS
          echo PLATFORMS: $PLATFORMS
          echo VARIANT: $VARIANT
          echo "::set-output name=tags::${TAGS//$', '/'%0A'}"
          echo "::set-output name=platforms::${PLATFORMS//$', '/'%0A'}"
          echo "::set-output name=variant::$VARIANT"

      - name: Generate Docker image metadata
        uses: docker/metadata-action@57396166ad8aefe6098280995947635806a0e6ea # tag=v4.1.1
        id: meta
        with:
          images: ${{ inputs.images }}
          tags: |
            ${{ steps.recipe.outputs.tags }}

      - name: Login to Docker Hub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # tag=v2.1.0
        with:
          registry: docker.io
          username: ${{ secrets.docker-hub-username }}
          password: ${{ secrets.docker-hub-access-token }}

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # tag=v2.1.0
        with:
          registry: ghcr.io
          username: ${{ secrets.ghcr-username }}
          password: ${{ secrets.ghcr-access-token }}

      - name: Build and push the Docker image from the specified Dockerfile
        id: docker_build
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5 # tag=v3.2.0
        with:
          context: ${{ matrix.workdir }}
          platforms: |
            ${{ steps.recipe.outputs.platforms }}
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # Well, turns out it doesn't support PAT yet. Please see https://github.com/peter-evans/dockerhub-description/issues/24 and https://github.com/docker/roadmap/issues/115
      #- name: Update repo description
      #  uses: peter-evans/dockerhub-description@v2.4.1
      #  with:
      #    username: ${{ secrets.docker-hub-username }}
      #    password: ${{ secrets.docker-hub-username }}
      #    repository: TO BE FILLED
