name: Specify Dockerfiles working directories

on:
  workflow_call:
    inputs:
      base-dir:
        required: true
        type: string
    outputs:
      workdirs:
        description: "List of working directories"
        value: ${{ jobs.specify-workdir.outputs.workdirs }}
      workdirs-array:
        description: "List of working directories in JSON Array"
        value: ${{ jobs.specify-workdir.outputs.workdirs-array }}

permissions:
  contents: read

jobs:
  specify-workdir:
    runs-on: ubuntu-latest

    outputs:
      workdirs: ${{ steps.workdirs.outputs.list }}
      workdirs-array: ${{ steps.array.outputs.result }}

    steps:
      - name: Check Out Repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
        with:
          fetch-depth: 0

      - name: Set up Node.js for generating JSON Array
        uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # tag=v3.3.0

      - name: Generate a list of changed Dockerfiles
        id: workdirs
        run: echo "::set-output name=list::$(git --no-pager diff --name-only HEAD^ ${{ inputs.base-dir }} | sed 's/\/Dockerfile//g' | sed ':a;N;$!ba;s/\n/ /g')"
        shell: bash

      - name: Generate a JSON array of list
        id: array
        run: echo "::set-output name=result::$(node -p 'JSON.stringify(process.argv.slice(1))' ${{ steps.workdirs.outputs.list }})"
